// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finalProject.Context;

#nullable disable

namespace finalProject.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("finalProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Women bags,Wallets,Bag Accessories,Men Bag,Luggage and Travel Gear",
                            Name = "Bags&Luggage"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Women Activewear,Men Activewear,Sports & Outdoor Shoes",
                            Name = "Sports&Outdoor"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Notebooks & Writing Pads,Filing products,Calenders & Cards,Art Supplies",
                            Name = "Office & School Supplies"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Women Accessories,Women Hair Accessories,Gender Neutral Accessories,Men Accessories",
                            Name = "Jewelry &Accessories"
                        });
                });

            modelBuilder.Entity("finalProject.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Women Vintage Coffee Brown Saddle Bag,Wide Strap Crossbody Bag,PU leather shoulder purse",
                            ImagePath = "~/Images/coffeebrownwomenbag.jpg",
                            Price = 450m,
                            Quantity = 4,
                            Title = "Women's vintage Saddle bag"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Hand-Painted Mushroom Pattern Print Corduroy Zipper Pouch, Portable Cosmetic Bag With Lining, Multifunctional Toiletry Organizer, Polyester Material, Unscented, Unisex-Adult, Non-Waterproof",
                            ImagePath = "~/Images/cosemeticbag.jpg",
                            Price = 110m,
                            Quantity = 10,
                            Title = "Portable Cosmetic Bag"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Book Backpack Flap Backpack Waterproof Portable For Travel Vacation Work Office Sport Gym Outdoor Nylon Casual For Student Boys College Student Teens Senior High School Student Rucksack Fathers Day Gifts Summer College Bag Dad School Bag FreshmanFor Books Back To School Multi-Functional Dorm University Man Bag School Backpack Students School Supplies Book Bag Large Capacity School Pencil Case Teacher Halloween Christmas Gift For Men Bag For School",
                            ImagePath = "~/Images/blackbookbackpack.jpg",
                            Price = 590m,
                            Quantity = 6,
                            Title = "Book Backpack"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "3pcs Sports Resistance Band",
                            ImagePath = "~/Images/resistanceband.jpg",
                            Price = 60m,
                            Quantity = 8,
                            Title = "Sports resistance band"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "1pair Women's Sports & Casual Chunky Sneakers, Versatile Chunky Sneakers",
                            ImagePath = "~/Images/sportssneaker.jpg",
                            Price = 850m,
                            Quantity = 3,
                            Title = "Sports Snesker"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "1pc 173*57*0.6cm TPE Yoga Mat For Beginners Exercise, Dancing, Non-Slip & Shock-Absorbing",
                            ImagePath = "~/Images/yogamat.jpg",
                            Price = 740m,
                            Quantity = 9,
                            Title = "Yoga mat"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "1pc Floral Pattern Printed Corduroy Pencil Case, Stationery Storage Bag, Double-Sided Printed Pen Case, Portable Multifunctional Office Stationery Pencil Organizer",
                            ImagePath = "~/Images/pencilcase.jpg",
                            Price = 60m,
                            Quantity = 7,
                            Title = "Pencil Case"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Description = "Flower Patterned Artistic Notebook With Fabric Cover, High Aesthetic Value",
                            ImagePath = "~/Images/notebook.jpg",
                            Price = 200m,
                            Quantity = 13,
                            Title = "Notebook"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            Description = "Elegant 1pc Simple Alloy Headband With Pearl & Flower & Rhinestone Decor For Women",
                            ImagePath = "~/Images/headband.jpg",
                            Price = 60m,
                            Quantity = 8,
                            Title = "Head band"
                        });
                });

            modelBuilder.Entity("finalProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("finalProject.Models.Product", b =>
                {
                    b.HasOne("finalProject.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("finalProject.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
